# Generated by Django 2.2.5 on 2020-06-26 21:53

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to=Posts.models.user_directory_path),
        ),
    ]
