# Generated by Django 2.2.5 on 2020-06-26 21:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, default='profile_pic/default.png', upload_to=accounts.models.user_directory_path),
        ),
    ]
